In [47]:
import pandas as pd
import numpy as np
import seaborn as sns

In [48]:
df = pd.read_csv('/Users/Bindhu sri/Downloads/Iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [49]:
df.shape

(150, 5)

In [50]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [51]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report, precision_score

In [52]:
df.duplicated().sum()

3

In [53]:
df=df .drop_duplicates()

In [54]:
df1=df
X = df.drop('species' , axis='columns')
Y = df['species']

In [55]:
x_train,x_test,y_train,y_test = train_test_split(X,Y, random_state=42,test_size=0.2)

In [56]:
model = LogisticRegression()  
model.fit(x_train,y_train)

LogisticRegression()

In [57]:
print((y_train == model1.predict(x_train)).sum()/len(x_train))
print((y_test == model1.predict(x_test)).sum()/len(x_test))

0.9829059829059829
0.9333333333333333


In [58]:
from sklearn.metrics import confusion_matrix
train_conf = confusion_matrix(y_train,model1.predict(x_train))
print(train_conf)
trainAcc_0 = train_conf[0][0]/train_conf[0].sum()
print(trainAcc_0)
trainAcc_1 = train_conf[1][1]/train_conf[1].sum()
print(trainAcc_1)

[[37  0  0]
 [ 0 38  2]
 [ 0  0 40]]
1.0
0.95


In [59]:
test_conf = confusion_matrix(y_test,model1.predict(x_test))
print(test_conf)
testAcc_0 = test_conf[0][0]/test_conf[0].sum()
print(testAcc_0)
testAcc_1 = test_conf[1][1]/test_conf[1].sum()
print(testAcc_1)

[[11  0  0]
 [ 0  9  1]
 [ 0  1  8]]
1.0
0.9


In [60]:
predictions = model1.predict(x_test)
print('\nAccuracy Score=',accuracy_score(ytest, predictions))


Accuracy Score= 0.9333333333333333


In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.90      0.90      0.90        10
   virginica       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

